version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5433:5432
    networks:
      - appnetwork
  web:
    build: ../
    command: bash -c "python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - appnetwork

networks:
  appnetwork:
