version: "3.9"

volumes:
  mentorship-data:

services:
  db:
    image: postgres
    volumes:
      - mentorship-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - appnetwork
  web:
    build: ../
    environment:
      - DB_HOST=db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000
    depends_on:
      - db
    networks:
      - appnetwork

networks:
  appnetwork:
