# Generated by Django 4.1 on 2022-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='origin_country',
            field=models.CharField(default='US', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='origin_year',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
