# Generated by Django 4.1 on 2022-09-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('website', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'Up to 10 employees'), ('S', '10 to 49 employees'), ('M', '50 to 99 employees'), ('L', 'Over 100 employees')], max_length=2)),
                ('headquarters', models.CharField(max_length=50)),
                ('founded', models.CharField(max_length=4)),
                ('specialties', models.TextField()),
            ],
        ),
    ]
