# Generated by Django 4.1 on 2022-09-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_stacks', models.CharField(max_length=200)),
                ('main_skills', models.CharField(max_length=200)),
                ('pay_range', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('website', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'Up to 10 employees'), ('S', '10 to 49 employees'), ('M', '50 to 99 employees'), ('L', 'Over 100 employees')], max_length=2)),
                ('headquarters', models.CharField(max_length=50)),
                ('founded', models.CharField(max_length=4)),
                ('specialties', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('experience_level', models.CharField(choices=[('INTERN', 'Internship'), ('ENTRY', 'Entry Level'), ('ASSOC', 'Associate')], max_length=6)),
                ('type', models.CharField(choices=[('FULL', 'Full-time'), ('PART', 'Part-time'), ('CONTR', 'Contract'), ('INTERN', 'Internship'), ('OTHER', 'Other')], max_length=6)),
                ('location', models.CharField(max_length=50)),
                ('requirements', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.company')),
            ],
        ),
    ]
