# Generated by Django 4.1 on 2022-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Desenvolvimento', max_length=50),
            preserve_default=False,
        ),
    ]
