# Generated by Django 4.1 on 2022-09-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_category_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
    ]
