# Generated by Django 4.1 on 2022-11-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Jobs'},
        ),
    ]
