# This is where you name you workflow
name: Lint&test-workflow

# Controls when the workflow will be triggered
# Push Triggers the workflow on push events for any branch
# workflow_dispatch Allows you to run this workflow manually from the Actions tab
on: 
 push: 
 workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially 
# or in parallel, in this case, theres a job called django-lint-test and 
# another called build-pub-container.
jobs:
  # job 1
  django-lint-test:
    runs-on: ubuntu-latest 
    steps:
    # this throws the branch in to the github machine so that it can work on it.
    - uses: actions/checkout@v3
    # first step 
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
    # second step, this one installs the dependencies for the project to work on the Github machine.    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
