# This is where you name you workflow
name: build&publish-workflow

# Controls when the workflow will be triggered
on:
  # Triggers the workflow on push events for a specific tag = *, when this happens it will call the Lint&test-workflow first.
  push:
    tags: '*'
  workflow_run:
    workflows: ["Lint&test-workflow"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially 
# or in parallel, in this case, theres a one job called build-pub-container.
jobs:
  # this is the job that builds and publishes the project.
  build-pub-container:
    if 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: saibrotech/mentorship-backend
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  
        registry: ghcr.io
