# This is where you name you workflow
name: build&publish-workflow

# Controls when the workflow will be triggered
on:
  # Triggers the workflow when the Lint&test workflow is completed sucessfully.
  workflow_run:
    workflows: ["Lint&test-workflow"]
    types:
      - success

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially 
# or in parallel, in this case, theres a one job called build-pub-container.
jobs:
  # this is the job that builds and publishes the project.
  build-pub-container:
    # this job will only run if it is accompanied with a tag named *
    if: ${{ github.ref_name == '*' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: saibrotech/mentorship-backend
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  
        registry: ghcr.io
